server:
  port: 8089


spring:
  application:
    name: currency-conversion-service


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#instance:
#  hostname: localhost
